# Generated by Django 3.1 on 2021-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30, verbose_name='방 이름')),
                ('leader_name', models.CharField(max_length=30, verbose_name='방장')),
                ('people_num', models.IntegerField(default=0, verbose_name='사람수')),
            ],
        ),
    ]
