# Generated by Django 3.2.8 on 2021-11-22 12:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0009_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=django.utils.timezone.now, size=30),
            preserve_default=False,
        ),
    ]
