# Generated by Django 3.2.8 on 2021-11-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0011_alter_game_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hangman_status',
            field=models.IntegerField(default=1),
        ),
    ]
