# Generated by Django 3.2.8 on 2021-11-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0012_game_hangman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='button_status',
            field=models.JSONField(default={'a': False, 'b': False, 'c': False, 'd': False, 'e': False, 'f': False, 'g': False, 'h': False, 'i': False, 'j': False, 'k': False, 'l': False, 'm': False, 'n': False, 'o': False, 'p': False, 'q': False, 'r': False, 's': False, 't': False, 'u': False, 'v': False, 'w': False, 'x': False, 'y': False, 'z': False}),
        ),
    ]
