# Generated by Django 3.2.8 on 2021-11-22 15:54

from django.db import migrations, models
import gamepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0013_game_button_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='button_status',
            field=models.JSONField(default=gamepage.models.default_button_dict),
        ),
    ]
