# Generated by Django 3.2.8 on 2021-11-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0014_alter_game_button_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='hangman_status',
        ),
    ]
