# Generated by Django 3.2.8 on 2021-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0015_auto_20211123_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hangman_status',
            field=models.IntegerField(default=1),
        ),
    ]
