# Generated by Django 3.1 on 2021-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0020_auto_20211123_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='answer',
            field=models.CharField(default='answer', max_length=30, verbose_name='정답'),
        ),
    ]
